-- =============================================
-- 多项目房源签约监测 Supabase 数据库架构
-- 所有项目共享同一张表，通过 project_code 区分
-- =============================================

-- 项目信息表
CREATE TABLE IF NOT EXISTS projects (
  code TEXT PRIMARY KEY,            -- 项目代码（英文标识，如 jiahua_junyuan）
  name TEXT NOT NULL,               -- 项目名称
  district TEXT,                    -- 所属区县
  location TEXT,                    -- 区位（二环内/二三环之间等）
  permit_no TEXT,                   -- 预售许可证号
  permit_date DATE,                 -- 发证时间
  developer TEXT,                   -- 开发企业
  address TEXT,                     -- 项目地址
  building_count INTEGER DEFAULT 0, -- 楼栋总数
  house_count INTEGER DEFAULT 0,    -- 房源总数
  source_url TEXT,                  -- 官网项目页URL
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 每日项目签约快照（整体数据）
CREATE TABLE IF NOT EXISTS daily_project_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code TEXT NOT NULL REFERENCES projects(code) ON DELETE CASCADE,
  snapshot_date DATE NOT NULL,      -- 快照日期
  signed_count INTEGER DEFAULT 0,   -- 已签约套数
  signed_area NUMERIC(14,2) DEFAULT 0, -- 已签约面积(㎡)
  avg_price NUMERIC(12,2) DEFAULT 0,   -- 成交均价(元/㎡)
  total_houses INTEGER DEFAULT 0,   -- 总套数
  total_area NUMERIC(14,2) DEFAULT 0,  -- 总面积
  extracted_at TIMESTAMPTZ,         -- 数据提取时间
  UNIQUE(project_code, snapshot_date)
);

-- 每日房源状态快照（明细数据）
CREATE TABLE IF NOT EXISTS house_status_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code TEXT NOT NULL REFERENCES projects(code) ON DELETE CASCADE,
  snapshot_date DATE NOT NULL,      -- 快照日期
  building TEXT NOT NULL,           -- 楼栋名称
  house_no TEXT NOT NULL,           -- 房号
  house_key TEXT NOT NULL,          -- 唯一键 (building + house_no)
  unit INTEGER,                     -- 单元号
  room TEXT,                        -- 房间号
  floor INTEGER,                    -- 楼层
  status TEXT NOT NULL,             -- 状态：可售/已签约/网上联机备案/已预订/不可售
  purpose TEXT,                     -- 用途：住宅/商业/办公等
  layout TEXT,                      -- 户型
  building_area NUMERIC(10,2),      -- 建筑面积(㎡)
  inner_area NUMERIC(10,2),         -- 套内面积(㎡)
  shared_area NUMERIC(10,2),        -- 分摊面积(㎡)
  unit_price NUMERIC(12,2),         -- 单价(元/㎡)
  total_price NUMERIC(14,2),        -- 总价(元)
  area_bucket TEXT,                 -- 面积段分组（如 88平、99平、127平等）
  extracted_at TIMESTAMPTZ,         -- 数据提取时间
  data_source TEXT,                 -- 数据来源：official/inferred/manual_corrected
  UNIQUE(project_code, snapshot_date, house_key)
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_daily_project_snapshots_project_code ON daily_project_snapshots(project_code);
CREATE INDEX IF NOT EXISTS idx_daily_project_snapshots_snapshot_date ON daily_project_snapshots(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_house_status_snapshots_project_code ON house_status_snapshots(project_code);
CREATE INDEX IF NOT EXISTS idx_house_status_snapshots_snapshot_date ON house_status_snapshots(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_house_status_snapshots_house_key ON house_status_snapshots(house_key);
CREATE INDEX IF NOT EXISTS idx_house_status_snapshots_status ON house_status_snapshots(status);

-- 启用 RLS（行级安全）
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_project_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE house_status_snapshots ENABLE ROW LEVEL SECURITY;

-- 公开读策略（匿名用户可读，用于前端展示）
CREATE POLICY "projects are viewable by everyone" ON projects
  FOR SELECT USING (true);

CREATE POLICY "daily snapshots are viewable by everyone" ON daily_project_snapshots
  FOR SELECT USING (true);

CREATE POLICY "house snapshots are viewable by everyone" ON house_status_snapshots
  FOR SELECT USING (true);

-- =============================================
-- 初始化示例数据（嘉华珺园）
-- 使用前请根据实际爬取数据替换
-- =============================================
-- INSERT INTO projects (code, name, district, location, permit_no, permit_date, developer, building_count, house_count, source_url)
-- VALUES (
--   'jiahua_junyuan',
--   '嘉华珺园',
--   '大兴区',
--   '五六环之间',
--   '京房售证字(2025)31号',
--   '2025-04-05',
--   '北京嘉会兴业置业有限公司',
--   16,
--   887,
--   'http://bjjs.zjw.beijing.gov.cn/eportal/ui?pageId=320794&projectID=7976631&systemID=2&srcId=1'
-- );
